
# ifndef __NNTAI_ICHATROBOT_3C94DD1F06C3446795EFFF2A19D5EBBF_H_INCLUDED
# define __NNTAI_ICHATROBOT_3C94DD1F06C3446795EFFF2A19D5EBBF_H_INCLUDED

# define NNT_CHATROBOT_HEADER_BEGIN \
NNT_BEGIN_HEADER_CXX \
NNT_BEGIN_NS(ai) \
NNT_BEGIN_NS(robot) \
NNT_BEGIN_NS(chat)

# define NNT_CHATROBOT_HEADER_END \
NNT_END_NS \
NNT_END_NS \
NNT_END_NS \
NNT_END_HEADER_CXX

# define NNT_CHATROBOT_BEGIN \
NNT_BEGIN_CXX \
NNT_BEGIN_NS(ai) \
NNT_BEGIN_NS(robot) \
NNT_BEGIN_NS(chat)

# define NNT_CHATROBOT_END \
NNT_END_NS \
NNT_END_NS \
NNT_END_NS \
NNT_END_CXX

# endif
