
# ifndef __NNT_KERNEL_DRIVERAPP_5fb7c4756bb245dea76e8a3035d281a1_H_INCLUDED
# define __NNT_KERNEL_DRIVERAPP_5fb7c4756bb245dea76e8a3035d281a1_H_INCLUDED

NNT_BEGIN_HEADER_CXX
NNT_BEGIN_NS(driver)

class App
{
public:

};

NNT_END_NS
NNT_END_HEADER_CXX

NNT_BEGIN_HEADER_C

# define NNT_DRIVER_MAIN __nnt_driver_main

NNT_EXTERN void NNT_DRIVER_MAIN ();

NNT_END_HEADER_C

# endif
