
# ifndef __NNT_SCRIPT_TINYSCHEME_4841EE686EC641C5831FA3B8F64A81BF_H_INCLUDED
# define __NNT_SCRIPT_TINYSCHEME_4841EE686EC641C5831FA3B8F64A81BF_H_INCLUDED

# import "Script+NNT.h"

NNT_BEGIN_HEADER_OBJC

NNTDECL_PRIVATE_HEAD(NNTTinyScheme);

@interface NNTTinyScheme : NNTObject <NNTScript> {
    NNTDECL_PRIVATE(NNTTinyScheme);
}

- (BOOL)executeUTF8String:(char const*)expr;

@end

NNT_END_HEADER_OBJC

# endif