
# ifndef __WSI_SCRIPT_TINYSCHEME_4841EE686EC641C5831FA3B8F64A81BF_H_INCLUDED
# define __WSI_SCRIPT_TINYSCHEME_4841EE686EC641C5831FA3B8F64A81BF_H_INCLUDED

# import "WSIScript.h"

WSI_BEGIN_HEADER_OBJC

WSIDECL_PRIVATE_HEAD(WSITinyScheme);

@interface WSITinyScheme : WSIObject <WSIScript> {
    WSIDECL_PRIVATE(WSITinyScheme);
}

- (BOOL)executeUTF8String:(char const*)expr;

@end

WSI_END_HEADER_OBJC

# endif