
# ifndef __WSI_EXECUTION_D2E9D5492BA64F64AD565794E62B902D_H_INCLUDED
# define __WSI_EXECUTION_D2E9D5492BA64F64AD565794E62B902D_H_INCLUDED

# ifndef __cplusplus
# error "please rename main.m to main.mm for support C++."
# endif

WSI_BEGIN_HEADER_OBJC

WSIUSE_CATEGORY(NSObject, WSI);
WSIUSE_CATEGORY(NSNumber, WSI);
WSIUSE_CATEGORY(NSData, WSI);
WSIUSE_CATEGORY(NSURL, WSI);
WSIUSE_CATEGORY(NSArray, WSI);
WSIUSE_CATEGORY(NSMutableArray, WSI);
WSIUSE_CATEGORY(NSDictionary, WSI);
WSIUSE_CATEGORY(NSMutableDictionary, WSI);
WSIUSE_CATEGORY(NSURLConnection, WSI);
WSIUSE_CATEGORY(NSString, WSI);
WSIUSE_CATEGORY(NSDate, WSI);
WSIUSE_CATEGORY(NSSet, WSI);

# ifdef WSI_USE_PRECISE

WSIUSE_CATEGORY(NSString, Regex);
WSIDECL_CATEGORY(NSString, Precise); WSIUSE_CATEGORY(NSString, Precise);

# endif

# ifdef WSI_TARGET_IOS

WSIUSE_CATEGORY(UIColor, WSI);
WSIUSE_CATEGORY(UIView, WSI);
WSIUSE_CATEGORY(UIWindow, WSI);
WSIUSE_CATEGORY(UIButton, WSI);
WSIUSE_CATEGORY(UILabel, WSI);
WSIUSE_CATEGORY(UIViewController, WSI);
WSIUSE_CATEGORY(UIImage, WSI);
WSIUSE_CATEGORY(UIDevice, WSI);
WSIUSE_CATEGORY(UIScreen, WSI);
WSIUSE_CATEGORY(UIImageView, WSI);
WSIUSE_CATEGORY(UIWebView, WSI);
WSIUSE_CATEGORY(UIScrollView, WSI);
WSIUSE_CATEGORY(UINavigationController, WSI);
WSIUSE_CATEGORY(NSObject, UITheme);
WSIUSE_CATEGORY(UITouch, WSI);
WSIUSE_CATEGORY(UITextField, WSI);

# endif

WSIUSE_CATEGORY(CALayer, WCA);
//WSIUSE_CATEGORY(CALayer, WCALayerFilters);

WSI_END_HEADER_OBJC

# endif
