// libwsi.idl : type library source for libwsi.dll
// This file will be processed by the MIDL compiler to produce the
// type library (libwsi.tlb).

[ uuid(9DCB1EC8-03FD-4C48-8601-39E890474F09), version(1.0) ]
library libwsi
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
};
