
# ifndef __NNT_STORE_LEVELDB_DAD3602259E6432DBD57CDDAEADFE833_H_INCLUDED
# define __NNT_STORE_LEVELDB_DAD3602259E6432DBD57CDDAEADFE833_H_INCLUDED

# import "DBMSNoSqlAbstract.h"

NNT_BEGIN_HEADER_OBJC

NNTDECL_PRIVATE_HEAD(NNTLevelDB);

@interface NNTLevelDB : DBMSNoSqlUrlAbstract {
    
    NNTDECL_PRIVATE(NNTLevelDB);
}

@end

NNT_END_HEADER_OBJC

# endif