
# ifndef __WSI_STORE_LEVELDB_DAD3602259E6432DBD57CDDAEADFE833_H_INCLUDED
# define __WSI_STORE_LEVELDB_DAD3602259E6432DBD57CDDAEADFE833_H_INCLUDED

# import "DBMSNoSqlAbstract.h"

WSI_BEGIN_HEADER_OBJC

WSIDECL_PRIVATE_HEAD(WSILevelDB);

@interface WSILevelDB : DBMSNoSqlUrlAbstract {
    
    WSIDECL_PRIVATE(WSILevelDB);
}

@end

WSI_END_HEADER_OBJC

# endif