#!/bin/sh

TARGET='wsi'.$1.'xcodeproj'
mkdir $TARGET
cd $TARGET
ln ../wsi.xcodeproj/project.pbxproj
mkdir project.xcworkspace
cd project.xcworkspace
ln ../../wsi.xcodeproj/project.xcworkspace/contents.xcworkspacedata
