#!/bin/sh

TARGET='nnt'.$1.'xcodeproj'
mkdir $TARGET
cd $TARGET
ln ../nnt.xcodeproj/project.pbxproj
mkdir project.xcworkspace
cd project.xcworkspace
ln ../../nnt.xcodeproj/project.xcworkspace/contents.xcworkspacedata
