
# ifndef __NNT_EXECUTION_D2E9D5492BA64F64AD565794E62B902D_H_INCLUDED
# define __NNT_EXECUTION_D2E9D5492BA64F64AD565794E62B902D_H_INCLUDED

# ifndef __cplusplus
//# error "please rename main.m to main.mm for support C++."
# endif

NNT_BEGIN_HEADER_OBJC

NNTUSE_CATEGORY(NSObject, NNT);
NNTUSE_CATEGORY(NSNumber, NNT);
NNTUSE_CATEGORY(NSData, NNT);
NNTUSE_CATEGORY(NSURL, NNT);
NNTUSE_CATEGORY(NSArray, NNT);
NNTUSE_CATEGORY(NSMutableArray, NNT);
NNTUSE_CATEGORY(NSDictionary, NNT);
NNTUSE_CATEGORY(NSMutableDictionary, NNT);
NNTUSE_CATEGORY(NSURLConnection, NNT);
NNTUSE_CATEGORY(NSString, NNT);
NNTUSE_CATEGORY(NSDate, NNT);
NNTUSE_CATEGORY(NSSet, NNT);

# ifdef NNT_USE_PRECISE

NNTUSE_CATEGORY(NSString, Regex);
NNTDECL_CATEGORY(NSString, Precise); NNTUSE_CATEGORY(NSString, Precise);

# endif

# ifdef NNT_TARGET_IOS

NNTUSE_CATEGORY(UIColor, NNT);
NNTUSE_CATEGORY(UIView, NNT);
NNTUSE_CATEGORY(UIWindow, NNT);
NNTUSE_CATEGORY(UIButton, NNT);
NNTUSE_CATEGORY(UILabel, NNT);
NNTUSE_CATEGORY(UIViewController, NNT);
NNTUSE_CATEGORY(UIImage, NNT);
NNTUSE_CATEGORY(UIDevice, NNT);
NNTUSE_CATEGORY(UIScreen, NNT);
NNTUSE_CATEGORY(UIImageView, NNT);
NNTUSE_CATEGORY(UIWebView, NNT);
NNTUSE_CATEGORY(UIScrollView, NNT);
NNTUSE_CATEGORY(UINavigationController, NNT);
NNTUSE_CATEGORY(NSObject, UITheme);
NNTUSE_CATEGORY(UITouch, NNT);
NNTUSE_CATEGORY(UIEvent, NNT);
NNTUSE_CATEGORY(UITextField, NNT);

# endif

NNTUSE_CATEGORY(CALayer, Ng);
//NNTUSE_CATEGORY(CALayer, NgLayerFilters);

NNT_END_HEADER_OBJC

# endif
