#!/bin/sh
PROGUARD=/opt/local/share/java/proguard.jar
LIBS=
OUTPUT=lib/wsi.jar
rm -f $OUTPUT
AJAR='/opt/local/share/java/android-sdk-mac_x86/platforms/android-10/android.jar'
java -Xmx1g -jar $PROGUARD -injars 'bin:lib/scala-library-2.9.jar(!META-INF/MANIFEST.MF,!library.properties)' -outjar $OUTPUT -libraryjars $AJAR @proguard.txt