# define PACKAGE_NAME "libspatialite-amalgamation"
# define PACKAGE_TARNAME     "libspatialite-amalgamation"
# define PACKAGE_VERSION     "2.3.1"
# define PACKAGE_STRING     "libspatialite-amalgamation 2.3.1"
# define PACKAGE_BUGREPORT     "wybosys@gmail.com"
# define PACKAGE     "libspatialite-amalgamation"
# define VERSION     "2.3.1"
# define STDC_HEADERS     1
# define HAVE_SYS_TYPES_H     1
# define HAVE_SYS_STAT_H     1
# define HAVE_STDLIB_H     1
# define HAVE_STRING_H     1
# define HAVE_MEMORY_H     1
# define HAVE_STRINGS_H     1
# define HAVE_INTTYPES_H     1
# define HAVE_STDINT_H     1
# define HAVE_UNISTD_H     1
# define HAVE_STDLIB_H     1
# define HAVE_STDIO_H     1
# define HAVE_STRING_H     1
# define HAVE_MEMORY_H     1
# define HAVE_MATH_H     1
# define HAVE_FLOAT_H     1
# define HAVE_FCNTL_H     1
# define HAVE_INTTYPES_H     1
# define HAVE_STDDEF_H     1
# define HAVE_STDINT_H     1
# define HAVE_SYS_TIME_H     1
# define HAVE_UNISTD_H     1
# define HAVE_DLFCN_H     1
# define TIME_WITH_SYS_TIME     1
# define HAVE_STRFTIME     1
# define HAVE_MEMSET     1
# define HAVE_SQRT     1
# define HAVE_STRCASECMP     1
# define HAVE_STRERROR     1
# define HAVE_STRNCASECMP     1
# define HAVE_STRSTR     1
# define HAVE_FDATASYNC     1
# define HAVE_FTRUNCATE     1
# define HAVE_GETCWD     1
# define HAVE_GETTIMEOFDAY     1
# define HAVE_LOCALTIME_R     1
# define HAVE_MEMMOVE     1
# define HAVE_STRERROR     1
