
# ifndef __WSI_CORE_NSREGEXLIBRARY_ECD53E1935FF4AFFB4FC6124981FF215_H_INCLUDED
# define __WSI_CORE_NSREGEXLIBRARY_ECD53E1935FF4AFFB4FC6124981FF215_H_INCLUDED

WSI_BEGIN_HEADER_OBJC

WSI_EXTERN NSString* kMatch_Email;
WSI_EXTERN NSString* kMatch_Password;
WSI_EXTERN NSString* kMatch_Cellphone;
WSI_EXTERN NSString* kMatch_Zipcode;
WSI_EXTERN NSString* kMatch_Telephone;

WSI_END_HEADER_OBJC

# endif