
SET (NNT_TRACE_CMAKE 1 CACHE BOOL "toggle trace debug")

FUNCTION (TRACE msg)
  IF (${NNT_TRACE_CMAKE})
    MESSAGE (STATUS "${msg}")
  ENDIF ()
ENDFUNCTION ()

FUNCTION (WARN msg)
  IF (${NNT_TRACE_CMAKE})
    MESSAGE (WARNING "${msg}")
  ENDIF ()
ENDFUNCTION ()

FUNCTION (FATAL msg)
  IF (${NNT_TRACE_CMAKE})
     MESSAGE (FATAL_ERROR "${msg}")
  ENDIF ()
ENDFUNCTION ()

SET (NNT_CFLAGS_DEBUG -D_DEBUG)
SET (CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} ${NNT_CFLAGS_DEBUG}")
SET (CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} ${NNT_CFLAGS_DEBUG}")
