
SET (NNT_BUILD_LIBRARY 1 CACHE BOOL "build the library" FORCE)

MACRO (source file)
  LIST (APPEND CURRENT_SOURCES ${file})
ENDMACRO (source)

IF (${NNT_BUILD_LIBRARY})
  INCLUDE_DIRECTORIES (AFTER "${PROJECT_SOURCE_DIR}/Classes")
  INCLUDE_DIRECTORIES (AFTER "${PROJECT_SOURCE_DIR}/Classes/Core")
  INCLUDE_DIRECTORIES (AFTER "${PROJECT_SOURCE_DIR}/3rd/Mac")
  INCLUDE_DIRECTORIES (AFTER "${PROJECT_SOURCE_DIR}/3rd/")
ENDIF (${NNT_BUILD_LIBRARY})
