
# ifndef __WSI_OA_DEFINES_FFAFCEDF963944FDBE493BB4141E3B8F_H_INCLUDED
# define __WSI_OA_DEFINES_FFAFCEDF963944FDBE493BB4141E3B8F_H_INCLUDED

WSI_BEGIN_HEADER_OBJC

WSI_EXTERN NSString* OA_KAIXIN_APPKEY;
WSI_EXTERN NSString* OA_KAIXIN_APPSECRET;

WSI_EXTERN NSString* OA_NETEASE_APPKEY;
WSI_EXTERN NSString* OA_NETEASE_APPSECRET;

WSI_EXTERN NSString* OA_SINA_APPKEY;
WSI_EXTERN NSString* OA_SINA_APPSECRET;

WSI_EXTERN NSString* OA_TENCENT_OPENWEIBO_APPKEY;
WSI_EXTERN NSString* OA_TENCENT_OPENWEIBO_APPSECRET;

WSI_EXTERN NSString* OA_TENCENT_OPENSNS_APPID;
WSI_EXTERN NSString* OA_TENCENT_OPENSNS_APPKEY;

WSI_EXTERN NSString* OA_RENREN_CLIENTID;
WSI_EXTERN NSString* OA_RENREN_CLIENTSECRET;

WSI_EXTERN NSString* OA_DOUBAN_APPKEY;
WSI_EXTERN NSString* OA_DOUBAN_APPSECRET;

WSI_EXTERN NSString* OA_SOHU_APPKEY;
WSI_EXTERN NSString* OA_SOHU_APPSECRET;

WSI_EXTERN NSString* OA_TAOBAO_APPKEY;
WSI_EXTERN NSString* OA_TAOBAO_APPSECRET;

WSI_EXTERN NSString* OA_ALIPAY_PARTENER;
WSI_EXTERN NSString* OA_ALIPAY_KEY;

WSI_EXTERN NSString* OA_WECHAT_PARTENER;

WSI_END_HEADER_OBJC

# endif