
# ifndef __NNT_OA_DEFINES_FFAFCEDF963944FDBE493BB4141E3B8F_H_INCLUDED
# define __NNT_OA_DEFINES_FFAFCEDF963944FDBE493BB4141E3B8F_H_INCLUDED

NNT_BEGIN_HEADER_OBJC

NNT_EXTERN NSString* OA_KAIXIN_APPKEY;
NNT_EXTERN NSString* OA_KAIXIN_APPSECRET;

NNT_EXTERN NSString* OA_NETEASE_APPKEY;
NNT_EXTERN NSString* OA_NETEASE_APPSECRET;

NNT_EXTERN NSString* OA_SINA_APPKEY;
NNT_EXTERN NSString* OA_SINA_APPSECRET;

NNT_EXTERN NSString* OA_TENCENT_OPENWEIBO_APPKEY;
NNT_EXTERN NSString* OA_TENCENT_OPENWEIBO_APPSECRET;

NNT_EXTERN NSString* OA_TENCENT_OPENSNS_APPID;
NNT_EXTERN NSString* OA_TENCENT_OPENSNS_APPKEY;

NNT_EXTERN NSString* OA_RENREN_CLIENTID;
NNT_EXTERN NSString* OA_RENREN_CLIENTSECRET;

NNT_EXTERN NSString* OA_DOUBAN_APPKEY;
NNT_EXTERN NSString* OA_DOUBAN_APPSECRET;

NNT_EXTERN NSString* OA_SOHU_APPKEY;
NNT_EXTERN NSString* OA_SOHU_APPSECRET;

NNT_EXTERN NSString* OA_TAOBAO_APPKEY;
NNT_EXTERN NSString* OA_TAOBAO_APPSECRET;

NNT_EXTERN NSString* OA_ALIPAY_PARTENER;
NNT_EXTERN NSString* OA_ALIPAY_KEY;

NNT_EXTERN NSString* OA_WECHAT_PARTENER;

NNT_END_HEADER_OBJC

# endif