
# ifndef __WSIAI_ICHATROBOT_3C94DD1F06C3446795EFFF2A19D5EBBF_H_INCLUDED
# define __WSIAI_ICHATROBOT_3C94DD1F06C3446795EFFF2A19D5EBBF_H_INCLUDED

# define WSI_CHATROBOT_HEADER_BEGIN \
WSI_BEGIN_HEADER_CXX \
WSI_BEGIN_NS(ai) \
WSI_BEGIN_NS(robot) \
WSI_BEGIN_NS(chat)

# define WSI_CHATROBOT_HEADER_END \
WSI_END_NS \
WSI_END_NS \
WSI_END_NS \
WSI_END_HEADER_CXX

# define WSI_CHATROBOT_BEGIN \
WSI_BEGIN_CXX \
WSI_BEGIN_NS(ai) \
WSI_BEGIN_NS(robot) \
WSI_BEGIN_NS(chat)

# define WSI_CHATROBOT_END \
WSI_END_NS \
WSI_END_NS \
WSI_END_NS \
WSI_END_CXX

# endif
