
# ifndef __WSI_COREPLOT_EXECUTION_32E9742B88F6434CAA2AFC9A2158F6D9_H_INCLUDED
# define __WSI_COREPLOT_EXECUTION_32E9742B88F6434CAA2AFC9A2158F6D9_H_INCLUDED

# import "CorePlot+WSI.h"

WSIUSE_CATEGORY(CPTextStyle, WSI);
WSIUSE_CATEGORY(CPColor, WSI);

WSIUSE_CATEGORY(NSString, CPTextStyleExtensions);
WSIUSE_CATEGORY(CPMutableNumericData, TypeConversion);
WSIUSE_CATEGORY(CPNumericData, TypeConversion);

# endif